# Generated by Django 5.2.1 on 2025-06-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_client_company_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('CLOTHING', 'Clothing'), ('FOOD', 'Food'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
